require 'sinatra/base'
require 'pg'
require 'sinatra/flash'
require './lib/database_connection'
require './database_connection_setup'

require './controllers/application_controller'
require './controllers/accommodation_controller'
require './controllers/booking_controller'
require './controllers/user_controller'
